services:
  postgres:
    image: postgres:16-alpine
    container_name: learnix-db
    environment:
      POSTGRES_DB: learnix
      POSTGRES_USER: learnix
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - learnix_data:/var/lib/postgresql/data

volumes:
  learnix_data: