
spring.datasource.url=jdbc:postgresql://localhost:5433/learnix
spring.datasource.username=learnix
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=8080

# -------------------------
# JWT (DEV ONLY)
# -------------------------
jwt.secret=bGVhcm5peC1kZXYtand0LXNlY3JldC1rZXktMjAyNi0wNC0yOC1taW5pbXVtLTMyLWJ5dGVz
